import { TooltipProvider } from '@/components/ui/tooltip';
import type { Metadata } from 'next';
import './globals.css';

import Sidebar from '@/components/Sidebar';
import Navbar from '@/components/Navbar';
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<TooltipProvider>
					<div className='flex min-h-screen w-full flex-col bg-muted/40'>
						<Sidebar />

						<div className='flex flex-col sm:gap-4 sm:py-4 sm:pl-14'>
							<Navbar />
							<main className='grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8'>
								{children}
							</main>
						</div>
					</div>
				</TooltipProvider>
			</body>
		</html>
	);
}
